name: build-macos-only

on:
  workflow_dispatch:
  push:
    branches:
      - macos-battery-fix

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
          cache-dependency-path: |
            core/go.sum

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.41.9
          cache: true

      - name: Get Flutter Dependency
        run: |
          flutter --version
          flutter pub get

      - name: Build DMG
        run: dart setup.dart macos -v

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FlClash-macos-arm64-dmg
          path: ./dist
          overwrite: true
